# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
# current_do_secret key is 95461f9a22d751b526dd69a77754bab85d389021987d38a956ef32676d26ad93
development:
  smtp_password: root
  smtp_username: Aerostarsito098BN-
  do_secret_key: f345d4453fb93276b44795f33f8ce9e8778c1638626db874dc09c38fd3e9f802
  secret_key_base: 815a91a6ee31dfe36a088ab70c8ebeded35d734fba9b848b34eac7e57688ffb723ef7a74e7b1a857e3f5ec98208b8c4b8b03acc49b0dcb15b121130759c347af
  paypal_host: https://www.sandbox.paypal.com
  app_host: <%= ENV["NGROK"] %>
test:
  secret_key_base: 38ee87319f85f05420af434cc7d16366a3d757ebbc074b38a5ef2cd62245aaa54d4d476401bb06744e106a035c13de35ea700346089e6855b0095874e0c68740

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  paypal_host: https://www.sandbox.paypal.com
  app_host: https://vm.iftech.cl
